import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import request from 'supertest';
import bcrypt from 'bcrypt';
import type { Express } from 'express';
import type { PrismaClient } from '@prisma/client';

const testDatabaseUrl = process.env.TEST_DATABASE_URL;
const postgres = testDatabaseUrl ? describe : describe.skip;

postgres('OpsFlow PostgreSQL business rules', () => {
  let app: Express; let prisma: PrismaClient; let adminToken: string; let operationsToken: string; let salesToken: string; let itemId: string; let sourceId: string; let destinationId: string;
  const auth = (token: string) => ({ Authorization: `Bearer ${token}` });
  const login = async (email: string) => { const response = await request(app).post('/api/auth/login').send({ email, password: 'Integration!2026' }); expect(response.status).toBe(200); return response.body.data.token as string; };
  const order = (code: string, quantity: number) => request(app).post('/api/orders').set(auth(salesToken)).send({ code, customerId: 'test-customer', locationId: sourceId, items: [{ itemId, batch: 'GENERAL', quantity }] });
  const transfer = (code: string, quantity: number) => request(app).post('/api/transfers').set(auth(operationsToken)).send({ code, sourceLocationId: sourceId, destinationLocationId: destinationId, itemId, batch: 'GENERAL', quantity });
  const inventoryWhere = () => ({ itemId_locationId_batch: { itemId, locationId: sourceId, batch: 'GENERAL' } });
  const destinationWhere = () => ({ itemId_locationId_batch: { itemId, locationId: destinationId, batch: 'GENERAL' } });

  beforeAll(async () => {
    process.env.DATABASE_URL = testDatabaseUrl!;
    const [{ createApp }, { prisma: db }, { RoleCode }] = await Promise.all([import('../src/app.js'), import('../src/config/prisma.js'), import('@prisma/client')]); app = createApp(); prisma = db;
    await prisma.inventoryTransaction.deleteMany(); await prisma.reservation.deleteMany(); await prisma.customerOrderItem.deleteMany(); await prisma.customerOrder.deleteMany(); await prisma.transfer.deleteMany(); await prisma.workOrderMaterial.deleteMany(); await prisma.workOrder.deleteMany(); await prisma.inventory.deleteMany(); await prisma.item.deleteMany(); await prisma.customer.deleteMany(); await prisma.location.deleteMany(); await prisma.category.deleteMany(); await prisma.user.deleteMany(); await prisma.role.deleteMany();
    const [adminRole, opsRole, salesRole] = await Promise.all([prisma.role.create({ data: { code: RoleCode.ADMIN, label: 'Admin' } }), prisma.role.create({ data: { code: RoleCode.OPERATIONS_USER, label: 'Operations' } }), prisma.role.create({ data: { code: RoleCode.SALES_USER, label: 'Sales' } })]);
    const passwordHash = await bcrypt.hash('Integration!2026', 12); await prisma.user.createMany({ data: [{ email: 'admin@test.local', name: 'Admin', passwordHash, roleId: adminRole.id }, { email: 'operations@test.local', name: 'Operations', passwordHash, roleId: opsRole.id }, { email: 'sales@test.local', name: 'Sales', passwordHash, roleId: salesRole.id }] });
    const category = await prisma.category.create({ data: { name: 'Test Components' } }); itemId = (await prisma.item.create({ data: { sku: 'TEST-STEEL', name: 'Test Steel Component', categoryId: category.id } })).id;
    sourceId = (await prisma.location.create({ data: { code: 'TEST-A', name: 'Source' } })).id; destinationId = (await prisma.location.create({ data: { code: 'TEST-B', name: 'Destination' } })).id; await prisma.customer.create({ data: { id: 'test-customer', name: 'Test Customer', email: 'customer@test.local' } });
    adminToken = await login('admin@test.local'); operationsToken = await login('operations@test.local'); salesToken = await login('sales@test.local'); const stored = await prisma.user.findUniqueOrThrow({ where: { email: 'admin@test.local' } }); expect(stored.passwordHash).not.toBe('Integration!2026'); expect(await bcrypt.compare('Integration!2026', stored.passwordHash)).toBe(true);
  });
  beforeEach(async () => { await prisma.inventoryTransaction.deleteMany(); await prisma.reservation.deleteMany(); await prisma.customerOrderItem.deleteMany(); await prisma.customerOrder.deleteMany(); await prisma.transfer.deleteMany(); await prisma.inventory.upsert({ where: inventoryWhere(), update: { physicalQuantity: 50, reservedQuantity: 0 }, create: { itemId, locationId: sourceId, batch: 'GENERAL', physicalQuantity: 50 } }); await prisma.inventory.upsert({ where: destinationWhere(), update: { physicalQuantity: 20, reservedQuantity: 0 }, create: { itemId, locationId: destinationId, batch: 'GENERAL', physicalQuantity: 20 } }); });
  afterAll(async () => { await prisma.$disconnect(); });

  it('rejects invalid login and unauthenticated access', async () => { expect((await request(app).post('/api/auth/login').send({ email: 'admin@test.local', password: 'invalid-pass' })).status).toBe(401); expect((await request(app).get('/api/inventory')).status).toBe(401); });
  it('prevents over-reservation without changing stock', async () => { const created = await order('SO-OVER', 60); const response = await request(app).post(`/api/orders/${created.body.data.id}/reserve`).set(auth(salesToken)); expect(response.status).toBe(409); expect(response.body.error.code).toBe('INSUFFICIENT_STOCK'); expect(Number((await prisma.inventory.findUniqueOrThrow({ where: inventoryWhere() })).reservedQuantity)).toBe(0); });
  it('prevents transfer dispatch when stock became unavailable', async () => { const created = await transfer('TR-INSUFFICIENT', 40); await prisma.inventory.update({ where: inventoryWhere(), data: { physicalQuantity: 30 } }); const response = await request(app).post(`/api/transfers/${created.body.data.id}/dispatch`).set(auth(operationsToken)); expect(response.status).toBe(409); expect(Number((await prisma.inventory.findUniqueOrThrow({ where: inventoryWhere() })).physicalQuantity)).toBe(30); });
  it('adds destination stock only on receipt and rejects duplicate receipt', async () => { const created = await transfer('TR-ONCE', 30); expect((await request(app).post(`/api/transfers/${created.body.data.id}/dispatch`).set(auth(operationsToken))).status).toBe(200); expect(Number((await prisma.inventory.findUniqueOrThrow({ where: destinationWhere() })).physicalQuantity)).toBe(20); expect((await request(app).post(`/api/transfers/${created.body.data.id}/receive`).set(auth(operationsToken))).status).toBe(200); expect(Number((await prisma.inventory.findUniqueOrThrow({ where: destinationWhere() })).physicalQuantity)).toBe(50); const duplicate = await request(app).post(`/api/transfers/${created.body.data.id}/receive`).set(auth(operationsToken)); expect(duplicate.status).toBe(409); expect(duplicate.body.error.code).toBe('TRANSFER_ALREADY_RECEIVED'); });
  it('enforces RBAC and lets an admin create a work order', async () => { const created = await transfer('TR-RBAC', 10); expect((await request(app).post(`/api/transfers/${created.body.data.id}/dispatch`).set(auth(salesToken))).status).toBe(403); const assignee = await prisma.user.findUniqueOrThrow({ where: { email: 'operations@test.local' } }); const workOrder = await request(app).post('/api/work-orders').set(auth(adminToken)).send({ code: 'WO-TEST', locationId: sourceId, assignedUserId: assignee.id, itemId, requiredQuantity: 80 }); expect(workOrder.status).toBe(201); expect(workOrder.body.data.materials[0].shortageQuantity).toBe(30); });
  it('serializes concurrent reservations so total reservations never exceed stock', async () => { await prisma.inventory.update({ where: inventoryWhere(), data: { physicalQuantity: 100, reservedQuantity: 0 } }); const [first, second] = await Promise.all([order('SO-RACE-A', 70), order('SO-RACE-B', 50)]); const outcomes = await Promise.all([request(app).post(`/api/orders/${first.body.data.id}/reserve`).set(auth(salesToken)), request(app).post(`/api/orders/${second.body.data.id}/reserve`).set(auth(salesToken))]); expect(outcomes.filter((response) => response.status === 200)).toHaveLength(1); expect(outcomes.filter((response) => response.status === 409)).toHaveLength(1); const line = await prisma.inventory.findUniqueOrThrow({ where: inventoryWhere() }); expect(Number(line.reservedQuantity)).toBe(70); expect(Number(line.reservedQuantity)).toBeLessThanOrEqual(Number(line.physicalQuantity)); });
});
