import { useState, type ReactNode } from 'react';
import { NavLink, useLocation, useNavigate } from 'react-router-dom';
import { Boxes, ChevronLeft, ClipboardList, LayoutDashboard, LogOut, Menu, PackageSearch, Repeat2, UserRound } from 'lucide-react';
import { useAuth } from '../hooks/useAuth';
const navigation = [
  { to: '/', label: 'Overview', icon: LayoutDashboard }, { to: '/inventory', label: 'Inventory', icon: Boxes }, { to: '/work-orders', label: 'Work Orders', icon: ClipboardList }, { to: '/transfers', label: 'Transfers', icon: Repeat2 }, { to: '/orders', label: 'Customer Orders', icon: PackageSearch },
];
const titles: Record<string, string> = { '/': 'Overview', '/inventory': 'Inventory', '/work-orders': 'Work Orders', '/transfers': 'Internal Transfers', '/orders': 'Customer Orders' };
export function AppLayout({ children }: { children: ReactNode }) {
  const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const { user, signOut } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const logout = () => { signOut(); navigate('/login'); };
  const sidebar = <aside className={`flex h-full flex-col bg-navy-900 text-slate-200 transition-all ${collapsed ? 'w-[74px]' : 'w-64'}`}><div className="flex h-16 items-center border-b border-white/10 px-4"><div className="flex min-w-0 items-center gap-2"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-blue-500 text-sm font-bold text-white">O</div>{!collapsed && <span className="truncate text-lg font-semibold tracking-tight text-white">OpsFlow</span>}</div><button onClick={() => setCollapsed((value) => !value)} className="ml-auto hidden rounded p-1 text-slate-400 hover:bg-white/10 hover:text-white lg:block" aria-label="Collapse sidebar"><ChevronLeft size={18} className={collapsed ? 'rotate-180' : ''} /></button></div><nav className="flex-1 space-y-1 p-3">{navigation.map(({ to, label, icon: Icon }) => <NavLink key={to} end={to === '/'} to={to} onClick={() => setMobileOpen(false)} className={({ isActive }) => `flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium ${isActive ? 'bg-blue-600 text-white shadow-sm' : 'text-slate-300 hover:bg-white/10 hover:text-white'}`} title={collapsed ? label : undefined}><Icon size={19} className="shrink-0" />{!collapsed && <span>{label}</span>}</NavLink>)}</nav><div className="border-t border-white/10 p-3"><div className="flex items-center gap-2 px-2 py-2"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-slate-700 text-xs font-semibold text-white">{user?.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</div>{!collapsed && <div className="min-w-0"><p className="truncate text-sm font-medium text-white">{user?.name}</p><p className="truncate text-xs text-slate-400">{user?.role.replace('_', ' ')}</p></div>}</div><button onClick={logout} className="mt-1 flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm text-slate-300 hover:bg-white/10 hover:text-white"><LogOut size={18} />{!collapsed && 'Sign out'}</button></div></aside>;
  return <div className="min-h-screen bg-slate-50"><div className="fixed inset-y-0 left-0 z-40 hidden lg:block">{sidebar}</div>{mobileOpen && <div className="fixed inset-0 z-40 bg-slate-950/45 lg:hidden" onClick={() => setMobileOpen(false)} />}{mobileOpen && <div className="fixed inset-y-0 left-0 z-50 lg:hidden">{sidebar}</div>}<main className={`min-h-screen transition-[margin] ${collapsed ? 'lg:ml-[74px]' : 'lg:ml-64'}`}><header className="sticky top-0 z-30 flex h-16 items-center border-b border-slate-200 bg-white/95 px-4 backdrop-blur md:px-6"><button onClick={() => setMobileOpen(true)} className="mr-3 rounded-lg p-2 text-slate-600 hover:bg-slate-100 lg:hidden"><Menu size={20} /></button><div><p className="text-xs text-slate-500">OpsFlow / Operations</p><h1 className="text-lg font-semibold text-slate-900">{titles[location.pathname] ?? 'Operations'}</h1></div><div className="ml-auto flex items-center gap-2 rounded-lg border border-slate-200 px-2.5 py-1.5 text-sm text-slate-600"><UserRound size={16} /><span className="hidden sm:inline">{user?.email}</span></div></header>{children}</main></div>;
}

